apiVersion: v1
kind: Template
metadata:
  name: s2i-scala
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: s2i-scala
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: scala:java8
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: java8
      git:
        uri: https://github.com/agello/s2i-scala.git
    strategy:
      dockerStrategy: {}
      type: Docker
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: scala
